name: "Release build"

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: ./global.json

    - name: Build
      run: ./Scripts/build.ps1
      shell: pwsh

    - name: Development Build Check
      shell: pwsh
      run: |
        if ($env:GitVersion_CommitsSinceVersionSource -ne "0") {
          Write-Output "::error:: This is a development build and should not be released. Did you forget to create a new tag for the release?"
          exit 1
        }

    - name: Zip Artifact
      run: 7z a -t7z -mx=9 -m0=lzma2 -ms=on -r -- ${{ format('xna-cncnet-client-{0}.7z', env.GitVersion_SemVer) }} ./Compiled/*
      shell: pwsh

    - name: Upload Final Artifact to the Release
      uses: softprops/action-gh-release@v2
      with:
        append_body: true
        files: ${{ format('xna-cncnet-client-{0}.7z', env.GitVersion_SemVer) }}
